import { DatabaseSchema } from './types';
import bcrypt from 'bcryptjs';
import { randomBytes } from 'crypto';

const DEFAULT_PASSWORD_HASH = bcrypt.hashSync('AdminPassword@2026!', 10);

// Placeholder only: this account authenticates exclusively via Supabase Auth
// (see authUserId). The hash is intentionally a random value no one knows.
const SUPABASE_ADMIN_PLACEHOLDER_HASH = bcrypt.hashSync(`supabase-only-${randomBytes(24).toString('hex')}`, 10);

export function getInitialSeedData(): DatabaseSchema {
  const now = new Date().toISOString();

  return {
    settings: {
      companyName: 'ABS Network Broadband SMC-Pvt-Ltd',
      shortName: 'ABS Network',
      legalRegistration: 'SMC-PVT-LTD',
      tagline: 'Ultra-Fast Fiber Broadband & Professional Networking Solutions',
      phone: '+92 3224180930',
      supportPhone:'+92 3224180930',
      whatsapp: '+92 3224180930',
      email: 'info@absnetwork.com.pk',
      salesEmail: 'info@absnetwork.com.pk',
      supportEmail: 'info@absnetwork.com.pk',
      address: 'Office 36, ST Main Nisbet Road Lahore',
      city: 'Lahore',
      businessHours: '24/7 Support | Sales: Mon - Sat (9:00 AM - 8:00 PM)',
      facebookUrl: 'https://www.facebook.com/absnetworksolution54',
      instagramUrl: 'https://www.instagram.com/absnetwork',
      heroHeadline: 'Fast, Reliable Fiber Internet For Everyone',
      heroSubheadline: 'Experience ultra-high-speed fiber broadband engineered for modern homes and demanding enterprises. Buffer-free streaming, low-latency gaming, and rock-solid reliability backed by 24/7 support.',
      footerNotice: 'ABS Network Broadband SMC-Pvt-Ltd is a licensed high-speed ISP and digital infrastructure provider committed to uninterrupted connectivity and professional networking solutions.',
      shopBannerText: 'Professional fiber optic and networking equipment for ISPs, enterprises, and home networks.',
      statsFiberCoverageKm: 850,
      statsActiveSubscribers: 28500,
      statsUptimeGuarantee: '99.98%',
      statsShopProductCount: 0,
      updatedAt: now,
    },
    users: [
      {
        id: 'usr_admin_01',
        name: 'System Super Admin',
        email: 'admin@absnetwork.pk',
        passwordHash: DEFAULT_PASSWORD_HASH,
        role: 'SUPER_ADMIN',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'usr_sales_01',
        name: 'Tariq Mehmood',
        email: 'sales@absnetwork.pk',
        passwordHash: DEFAULT_PASSWORD_HASH,
        role: 'SALES_MANAGER',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'usr_support_01',
        name: 'Zainab Fatima',
        email: 'support@absnetwork.pk',
        passwordHash: DEFAULT_PASSWORD_HASH,
        role: 'SUPPORT_AGENT',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'usr_content_01',
        name: 'Bilal Khan',
        email: 'content@absnetwork.pk',
        passwordHash: DEFAULT_PASSWORD_HASH,
        role: 'CONTENT_MANAGER',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'usr_security_01',
        name: 'Hamza Farooq',
        email: 'security@absnetwork.pk',
        passwordHash: DEFAULT_PASSWORD_HASH,
        role: 'SECURITY_AUDITOR',
        isActive: true,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'usr_supabase_super_01',
        name: 'absnetwork951',
        email: 'absnetwork951@gmail.com',
        passwordHash: SUPABASE_ADMIN_PLACEHOLDER_HASH,
        role: 'SUPER_ADMIN',
        isActive: true,
        authUserId: '32a4f677-0c9f-418a-9b95-ef0c3368f0a0',
        createdAt: now,
        updatedAt: now,
      },
    ],
    sessions: [],
    packages: [
      {
        id: 'pkg_fiber_15',
        name: 'ABS Home Fiber 15',
        slug: 'abs-home-fiber-15mbps',
        category: 'residential',
        speedMbps: 15,
        uploadSpeedMbps: 15,
        pricePkr: 1999,
        priceType: 'fixed',
        priceLabel: 'PKR 1,999 + TAX',
        billingPeriod: 'Monthly',
        installationFeePkr: 0,
        dataLimit: 'Truly Unlimited',
        features: [
          '15 Mbps Symmetric Fiber Speed',
          'Unlimited High-Speed Data (No FUP)',
          'Free Optical Fiber Installation',
          '24/7 Helpdesk Support',
        ],
        routerIncluded: true,
        isPopular: false,
        isActive: true,
        displayOrder: 1,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'pkg_fiber_20',
        name: 'ABS Starter Fiber',
        slug: 'abs-starter-fiber-20mbps',
        category: 'residential',
        speedMbps: 20,
        uploadSpeedMbps: 20,
        pricePkr: 2499,
        priceType: 'fixed',
        priceLabel: 'PKR 2,499 + TAX',
        billingPeriod: 'Monthly',
        installationFeePkr: 0,
        dataLimit: 'Truly Unlimited',
        features: [
          '20 Mbps Symmetric Fiber Speed',
          'Unlimited High-Speed Data (No FUP)',
          'Optimized for HD Streaming & Browsing',
          'Free Optical Fiber Installation',
          '24/7 Helpdesk Support',
        ],
        routerIncluded: true,
        isPopular: false,
        isActive: true,
        displayOrder: 2,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'pkg_fiber_30',
        name: 'ABS Turbo Stream',
        slug: 'abs-turbo-stream-30mbps',
        category: 'residential',
        speedMbps: 30,
        uploadSpeedMbps: 30,
        pricePkr: 3499,
        priceType: 'fixed',
        priceLabel: 'PKR 3,499 + TAX',
        billingPeriod: 'Monthly',
        installationFeePkr: 0,
        dataLimit: 'Truly Unlimited',
        features: [
          '30 Mbps Symmetric Fiber Speed',
          'Uncapped 4K Ultra-HD Streaming',
          'Priority Routing for Zoom & Teams',
          'Round-the-Clock Priority Phone Support',
        ],
        routerIncluded: true,
        isPopular: true,
        isActive: true,
        displayOrder: 3,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'pkg_fiber_50',
        name: 'ABS Ultra Gamer',
        slug: 'abs-ultra-gamer-50mbps',
        category: 'gaming',
        speedMbps: 50,
        uploadSpeedMbps: 50,
        pricePkr: 5699,
        priceType: 'fixed',
        priceLabel: 'PKR 5,699 + TAX',
        billingPeriod: 'Monthly',
        installationFeePkr: 0,
        dataLimit: 'Truly Unlimited',
        features: [
          '50 Mbps Ultra-Low Latency Fiber',
          'Direct BGP Peering to Steam & Discord',
          'Bufferbloat Grade-A Gaming Optimization',
          '24/7 Gaming Support Desk',
        ],
        routerIncluded: true,
        routerDetails: 'Wi-Fi 6 AX3000 Low-Latency Gigabit Gateway',
        isPopular: false,
        isActive: true,
        displayOrder: 4,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'pkg_biz_100',
        name: 'ABS Business Prime',
        slug: 'abs-business-prime-100mbps',
        category: 'business',
        speedMbps: 100,
        uploadSpeedMbps: 100,
        pricePkr: 11799,
        priceType: 'fixed',
        priceLabel: 'PKR 11,799 + TAX',
        billingPeriod: 'Monthly',
        installationFeePkr: 0,
        dataLimit: '1:1 Dedicated',
        features: [
          '100 Mbps',
          '2 Usable Public Static IPv4 Addresses',
          'Corporate Optical Fiber Direct Run',
          'Technical Account Manager',
          '24/7 Priority NOC Support',
        ],
        routerIncluded: true,
        routerDetails: 'Enterprise Dual-WAN Managed Fiber Gateway',
        isPopular: false,
        isActive: true,
        displayOrder: 5,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'pkg_biz_200',
        name: 'ABS Business Pro',
        slug: 'abs-business-pro-200mbps',
        category: 'business',
        speedMbps: 200,
        uploadSpeedMbps: 200,
        pricePkr: 0,
        priceType: 'contact',
        priceLabel: 'Please contact us for rates.',
        billingPeriod: 'Monthly',
        installationFeePkr: 0,
        dataLimit: '1:1 Dedicated',
        features: [
          '200 Mbps 1:1 Bandwidth',
          'Public Static IP Pool (Optional)',
          'Custom BGP Routing Options',
          'Priority NOC & Account Engineer',
          '99.98% SLA Uptime Contract',
        ],
        routerIncluded: true,
        routerDetails: 'Enterprise Dual-WAN Managed Fiber Gateway',
        isPopular: false,
        isActive: true,
        displayOrder: 6,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'pkg_ent_300',
        name: 'ABS Enterprise Apex',
        slug: 'abs-enterprise-apex-300mbps',
        category: 'enterprise',
        speedMbps: 300,
        uploadSpeedMbps: 300,
        pricePkr: 0,
        priceType: 'contact',
        priceLabel: 'Please contact us for rates.',
        billingPeriod: 'Monthly',
        installationFeePkr: 0,
        dataLimit: 'Carrier Grade',
        features: [
          '300 Mbps Carrier-Grade Optical Bandwidth',
          'Redundant Ring Architecture Fiber Loop',
          '/29 Subnet (5 Public Static IPs)',
          'Enterprise DDoS Mitigation & Protection',
          '24/7 Tier-3 NOC Engineering Access',
        ],
        routerIncluded: true,
        routerDetails: 'Rackmount Carrier Edge Layer-3 Gateway',
        isPopular: false,
        isActive: true,
        displayOrder: 7,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'pkg_ent_500',
        name: 'ABS Enterprise Titan',
        slug: 'abs-enterprise-titan-500mbps',
        category: 'enterprise',
        speedMbps: 500,
        uploadSpeedMbps: 500,
        pricePkr: 0,
        priceType: 'contact',
        priceLabel: 'Please contact us for rates.',
        billingPeriod: 'Monthly',
        installationFeePkr: 0,
        dataLimit: 'Carrier Grade',
        features: [
          '500 Mbps Carrier-Grade Bandwidth',
          'Redundant Multi-Path Fiber Routing',
          'Custom IP Subnet & BGP Peering',
          'NOC Lead & Account Engineer',
          'Customized Uptime SLA Contract',
        ],
        routerIncluded: true,
        routerDetails: 'Rackmount Carrier Edge Layer-3 Gateway',
        isPopular: false,
        isActive: true,
        displayOrder: 8,
        createdAt: now,
        updatedAt: now,
      },
    ],
    services: [
      {
        id: 'srv_network_design',
        title: 'Network Design & Architecture',
        slug: 'network-design-architecture',
        category: 'networking',
        shortDescription: 'High-performance LAN/WAN topology planning, VLAN segmentation, and enterprise infrastructure blueprints built for resilience and scalability.',
        fullDescription: 'ABS Network engineers design robust network architectures that keep your business online and efficient. Our team plans LAN/WAN topologies, IP addressing, subnetting, and full VLAN architectures, with comprehensive documentation and mapping delivered at every stage.',
        iconName: 'Network',
        badge: 'Core Infrastructure',
        imageUrl: '/net2.jpg',
        imageAlt: 'Enterprise Network Architecture and Topology Planning',
        capabilities: [
          'LAN/WAN design & topology planning',
          'IP addressing, subnetting & VLAN architecture',
          'Network segmentation & traffic isolation',
          'Comprehensive network documentation & mapping',
        ],
        features: [
          'LAN/WAN design & topology planning',
          'IP addressing, subnetting & VLAN architecture',
          'Network segmentation & traffic isolation',
          'Comprehensive network documentation & mapping',
        ],
        ctaLabel: 'Design My Network',
        whatsappMessage: 'Hello ABS Network, I am interested in your Network Design & Architecture services. I would like to discuss my requirements.',
        isFeatured: true,
        isPublished: true,
        displayOrder: 1,
        seoTitle: 'Network Design & Architecture Services | ABS Network',
        seoDescription: 'Professional LAN/WAN design, VLAN segmentation, and enterprise network architecture engineered for resilience and scalability by ABS Network.',
        seoKeywords: ['network design', 'LAN WAN', 'VLAN', 'network architecture', 'ISB networking'],
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_office_network',
        title: 'Office Network Installation',
        slug: 'office-network-installation',
        category: 'networking',
        shortDescription: 'End-to-end office networking rollout including rack assembly, patch panel dressing, switch configuration, and certified cable testing.',
        fullDescription: 'Complete office network deployment handled by certified engineers. We install structured cabling, network racks, patch panels, and switches, then test and label every drop for a clean, reliable, and maintainable network.',
        iconName: 'Building2',
        badge: 'On-Site Deployment',
        imageUrl: '/net1.jpg',
        imageAlt: 'Office Network Installation and Structured Rack Management',
        capabilities: [
          'Complete office network deployment',
          'Structured cabling, patch panels & rack setup',
          'Switch & access point installation',
          'Cable testing, labeling & clean management',
        ],
        features: [
          'Complete office network deployment',
          'Structured cabling, patch panels & rack setup',
          'Switch & access point installation',
          'Cable testing, labeling & clean management',
        ],
        ctaLabel: 'Request Site Survey',
        whatsappMessage: 'Hello ABS Network, I need complete Office Network Installation and deployment support.',
        isFeatured: false,
        isPublished: true,
        displayOrder: 2,
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_internet_infra',
        title: 'Internet Infrastructure & Multi-WAN',
        slug: 'internet-infrastructure',
        category: 'internet',
        shortDescription: 'Redundant ISP connectivity, dedicated fiber links, automated failover, dynamic load balancing, and bandwidth queue management.',
        fullDescription: 'Zero-downtime internet begins with redundant connectivity. ABS Network designs multi-WAN internet infrastructure with automatic failover, load balancing, and bandwidth queue management so your business stays online even when a single link fails.',
        iconName: 'Globe',
        badge: 'Zero Downtime',
        imageUrl: '/hero3.jpg',
        imageAlt: 'Enterprise Internet Infrastructure and Multi-WAN Failover',
        capabilities: [
          'ISP connectivity & dedicated fiber routing',
          'Multi-WAN load balancing & automatic failover',
          'Bandwidth management & traffic shaping',
          'Real-time network latency & uptime monitoring',
        ],
        features: [
          'ISP connectivity & dedicated fiber routing',
          'Multi-WAN load balancing & automatic failover',
          'Bandwidth management & traffic shaping',
          'Real-time network latency & uptime monitoring',
        ],
        ctaLabel: 'Optimize Internet',
        whatsappMessage: 'Hello ABS Network, I am interested in your Internet Infrastructure and Multi-WAN failover solutions.',
        isFeatured: true,
        isPublished: true,
        displayOrder: 3,
        seoTitle: 'Internet Infrastructure & Multi-WAN Solutions | ABS Network',
        seoDescription: 'Redundant ISP connectivity, dedicated fiber links, automated failover, and load balancing for zero-downtime enterprise internet.',
        seoKeywords: ['multi-wan', 'internet infrastructure', 'failover', 'load balancing', 'ISP connectivity'],
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_troubleshooting',
        title: 'Network Troubleshooting & Optimization',
        slug: 'network-troubleshooting',
        category: 'networking',
        shortDescription: 'Fast diagnosis and root-cause resolution for packet loss, DNS issues, IP conflicts, Wi-Fi interference, and bottlenecked throughput.',
        fullDescription: 'When your network is slow or unstable, ABS Network engineers diagnose and resolve the root cause fast. We fix packet loss, DNS and DHCP issues, IP conflicts, Wi-Fi interference, and tune throughput and latency for peak performance.',
        iconName: 'Activity',
        badge: 'Rapid Resolution',
        imageUrl: '/net.jpg',
        imageAlt: 'Network Troubleshooting and Packet Analysis',
        capabilities: [
          'Slow network & bandwidth bottleneck resolution',
          'Packet loss, DNS & DHCP conflict debugging',
          'Wi-Fi coverage & routing fault remediation',
          'Comprehensive throughput & latency tuning',
        ],
        features: [
          'Slow network & bandwidth bottleneck resolution',
          'Packet loss, DNS & DHCP conflict debugging',
          'Wi-Fi coverage & routing fault remediation',
          'Comprehensive throughput & latency tuning',
        ],
        ctaLabel: 'Fix My Network',
        whatsappMessage: 'Hello ABS Network, I am facing network issues and need urgent network troubleshooting assistance.',
        isFeatured: false,
        isPublished: true,
        displayOrder: 4,
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_cisco',
        title: 'Cisco Network Solutions',
        slug: 'cisco-network-solutions',
        category: 'cisco',
        shortDescription: 'Certified configuration and management for Cisco Catalyst switches, ISR/ASR routers, Inter-VLAN routing, OSPF, ACLs, and port security.',
        fullDescription: 'Our certified engineers configure and manage Cisco Catalyst switches, ISR/ASR routers, VLANs, trucks, Inter-VLAN routing, static routing, OSPF, EIGRP, NAT, and ACLs. We also harden and optimize your Cisco environment for performance and security.',
        iconName: 'Cpu',
        badge: 'Certified Engineers',
        imageUrl: '/images/shop/switches.jpg',
        imageAlt: 'Cisco Router and Switch Enterprise Configuration',
        capabilities: [
          'Cisco switch & router configuration',
          'VLANs, 802.1Q trunks, access ports & Inter-VLAN routing',
          'Static routing, OSPF, EIGRP, NAT & ACL security',
          'STP, Port Security, device hardening & maintenance',
        ],
        features: [
          'Cisco switch configuration',
          'Cisco router configuration',
          'VLAN configuration',
          'Trunk configuration',
          'Access ports',
          'Inter-VLAN routing',
          'DHCP configuration',
          'Static routing',
          'OSPF & EIGRP',
          'NAT & ACL configuration',
          'Port security & STP',
          'Cisco network optimization',
        ],
        ctaLabel: 'Contact an Engineer',
        whatsappMessage: 'Hello ABS Network, I am interested in Cisco networking services and router/switch configuration.',
        isFeatured: true,
        isPublished: true,
        displayOrder: 5,
        seoTitle: 'Cisco Network Solutions | ABS Network',
        seoDescription: 'Certified Cisco Catalyst switch and router configuration, Inter-VLAN routing, OSPF, ACLs, and port security from ABS Network engineers.',
        seoKeywords: ['cisco', 'cisco routing', 'cisco switch', 'catalyst', 'OSPF', 'network engineer'],
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_mikrotik',
        title: 'MikroTik Network Solutions',
        slug: 'mikrotik-network-solutions',
        category: 'mikrotik',
        shortDescription: 'Expert RouterOS deployment for PPPoE servers, Hotspot gateways, multi-WAN PCC load balancing, VPN tunnels, and advanced firewall filters.',
        fullDescription: 'MikroTik is the backbone of cost-effective ISP and enterprise routing. ABS Network specializes in RouterOS configuration, PPPoE servers, hotspot portals, multi-WAN PCC load balancing, queue management, VPN tunnels, and firewall filter rules.',
        iconName: 'Router',
        badge: 'RouterOS Specialists',
        imageUrl: '/images/shop/routers.jpg',
        imageAlt: 'MikroTik RouterOS Configuration and Bandwidth Management',
        capabilities: [
          'RouterOS configuration, PPPoE server/client & DHCP',
          'Multi-WAN failover, PCC load balancing & policy routing',
          'Queue tree bandwidth management & hotspot portals',
          'Site-to-site WireGuard, IPsec & OpenVPN tunnels',
        ],
        features: [
          'MikroTik router configuration',
          'RouterOS configuration',
          'PPPoE server & PPPoE client',
          'DHCP, NAT & Firewall filter rules',
          'VLAN & Routing table setup',
          'Bandwidth management & Simple/Tree queues',
          'Hotspot captive portal',
          'Load balancing & Failover Multi-WAN',
          'VPN & Remote access security',
          'Wireless configuration & ISP setups',
        ],
        ctaLabel: 'Configure My Network',
        whatsappMessage: 'Hello ABS Network, I am interested in MikroTik configuration and networking services.',
        isFeatured: true,
        isPublished: true,
        displayOrder: 6,
        seoTitle: 'MikroTik Network Solutions | ABS Network',
        seoDescription: 'Expert RouterOS configuration, PPPoE servers, multi-WAN PCC load balancing, VPN tunnels, and firewall filters by ABS Network.',
        seoKeywords: ['mikrotik', 'routeros', 'pppoe', 'hotspot', 'load balancing', 'vpn'],
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_windows_server',
        title: 'Windows Server & Active Directory',
        slug: 'windows-server-administration',
        category: 'servers',
        shortDescription: 'Enterprise Windows Server setup, Domain Controller migration, Group Policy enforcement, File/Print servers, IIS, and Microsoft 365 hybrid sync.',
        fullDescription: 'Reliable Windows Server management keeps your business identity and file services running. ABS Network installs and migrates Windows Server, manages Active Directory Domain Services, enforces Group Policy, and configures DNS, DHCP, IIS, and Remote Desktop Services.',
        iconName: 'Server',
        badge: 'Systems Engineering',
        imageUrl: '/why.jpg',
        imageAlt: 'Windows Server and Active Directory Domain Management',
        capabilities: [
          'Windows Server installation, migration & patching',
          'Active Directory Domain Services & OU architecture',
          'Group Policy Objects (GPO) security & access rights',
          'DNS, DHCP, IIS web server & Remote Desktop Services',
        ],
        features: [
          'Windows Server installation & migration',
          'Domain controller setup & AD migration',
          'User & Group management with OUs',
          'Group Policy (GPO) deployment',
          'Domain joining & Windows authentication',
          'File server, Print server, DHCP & DNS roles',
          'IIS and Remote Desktop Services (RDS)',
          'Microsoft 365 & hybrid cloud integration',
        ],
        ctaLabel: 'Manage Windows Server',
        whatsappMessage: 'Hello ABS Network, I am interested in Windows Server and Active Directory services.',
        isFeatured: true,
        isPublished: true,
        displayOrder: 7,
        seoTitle: 'Windows Server & Active Directory Services | ABS Network',
        seoDescription: 'Windows Server installation, Active Directory, Group Policy, IIS, and Microsoft 365 hybrid sync from ABS Network system engineers.',
        seoKeywords: ['windows server', 'active directory', 'domain controller', 'group policy', 'microsoft 365'],
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_linux_server',
        title: 'Linux Server Administration',
        slug: 'linux-server-administration',
        category: 'servers',
        shortDescription: 'Hardened Linux deployments (Ubuntu, Debian, RHEL/Rocky), Nginx/Apache reverse proxies, Docker containerization, databases, and automated backups.',
        fullDescription: 'ABS Network deploys and hardens Linux servers running Ubuntu, Debian, and RHEL/Rocky. We configure Nginx and Apache reverse proxies, Docker containers, MySQL and PostgreSQL databases, SSL automation, firewalls, and automated backups.',
        iconName: 'Terminal',
        badge: 'DevOps & SysAdmin',
        imageUrl: '/hero4.jpg',
        imageAlt: 'Linux Server Administration and Container Infrastructure',
        capabilities: [
          'Ubuntu, Debian & RHEL/CentOS server deployment',
          'Nginx, Apache, PHP-FPM, MySQL & PostgreSQL setup',
          'Docker containers, reverse proxy & SSL automation',
          'SSH hardening, UFW/iptables firewalls & backup cron',
        ],
        features: [
          'Ubuntu Server & Debian configuration',
          'CentOS/RHEL-compatible environments',
          'SSH hardening & user permissions',
          'Nginx & Apache reverse proxies',
          'MySQL/MariaDB & PostgreSQL databases',
          'Docker containerization & stacks',
          'SSL certificates & automated renewal',
          'Server hardening, monitoring & backups',
        ],
        ctaLabel: 'Setup Linux Server',
        whatsappMessage: 'Hello ABS Network, I am interested in Linux Server Administration and deployment services.',
        isFeatured: false,
        isPublished: true,
        displayOrder: 8,
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_office_it',
        title: 'Office IT & Technical Services',
        slug: 'office-it-technical-services',
        category: 'it-support',
        shortDescription: 'Get professional technical assistance for your office network, computers, servers, internet, printers, and complete IT workplace infrastructure.',
        fullDescription: 'Your on-site IT engineering team. ABS Network provides complete office IT setup, computer, printer, and scanner configuration, hardware repairs, Windows troubleshooting, email and Wi-Fi setup, and preventive maintenance with on-demand SLA support.',
        iconName: 'Wrench',
        badge: 'On-Site & Remote',
        imageUrl: '/why1.jpg',
        imageAlt: 'On-Site IT Engineering and Office Support',
        capabilities: [
          'Complete office IT hardware & software setup',
          'Computer, printer, scanner & peripheral configuration',
          'Hardware repairs, Windows troubleshooting & diagnostics',
          'Preventive IT maintenance & on-demand SLA support',
        ],
        features: [
          'Complete office IT setup',
          'Office network deployment',
          'Computer configuration',
          'Printer & scanner installation',
          'Wi-Fi & router setup',
          'User account setup & email configuration',
          'Software installation & licensing',
          'Hardware & Windows troubleshooting',
          'Preventive maintenance visits',
          'On-site & remote engineer dispatch',
        ],
        ctaLabel: 'Get IT Support',
        whatsappMessage: 'Hello ABS Network, I need technical IT support and on-site engineering for my office.',
        isFeatured: true,
        isPublished: true,
        displayOrder: 9,
        seoTitle: 'Office IT & Technical Services | ABS Network',
        seoDescription: 'Professional on-site and remote IT support for offices: computers, printers, servers, internet, and complete IT workplace infrastructure.',
        seoKeywords: ['it support', 'office it', 'computer repair', 'managed it', 'on-site engineer'],
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_cybersecurity',
        title: 'Network Security & Cybersecurity',
        slug: 'network-security-cybersecurity',
        category: 'cybersecurity',
        shortDescription: 'Defense-in-depth infrastructure hardening, stateful firewall rules, VLAN isolation, secure VPNs, endpoint protection, and security auditing.',
        fullDescription: 'Protect your infrastructure with a defense-in-depth strategy. ABS Network configures MikroTik and Cisco firewall rules, network segmentation and secure VLANs, encrypted remote-access and site-to-site VPNs, endpoint security, and performs security audits.',
        iconName: 'ShieldCheck',
        badge: 'Infrastructure Hardening',
        imageUrl: '/hero2.jpg',
        imageAlt: 'Network Security, Firewalls and Enterprise Hardening',
        capabilities: [
          'MikroTik & Cisco firewall rule configuration',
          'Network segmentation & secure VLAN boundaries',
          'Encrypted IPsec & WireGuard remote access VPNs',
          'Infrastructure security assessments & backup audits',
        ],
        features: [
          'Firewall configuration',
          'MikroTik firewall & Cisco security',
          'Network segmentation & VLAN security',
          'Access control policies',
          'Remote access & site-to-site VPNs',
          'Endpoint security & server hardening',
          'Secure enterprise Wi-Fi (WPA3/Enterprise)',
          'Security auditing & vulnerability assessments',
        ],
        ctaLabel: 'Secure My Network',
        whatsappMessage: 'Hello ABS Network, I am interested in your network security and cybersecurity services.',
        isFeatured: true,
        isPublished: true,
        displayOrder: 10,
        seoTitle: 'Network Security & Cybersecurity Services | ABS Network',
        seoDescription: 'Infrastructure hardening, firewall configuration, VLAN isolation, secure VPNs, and security auditing from ABS Network.',
        seoKeywords: ['cybersecurity', 'firewall', 'network security', 'vpn', 'security audit', 'vulnerability'],
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_wireless',
        title: 'Enterprise Wi-Fi & Wireless',
        slug: 'enterprise-wifi-wireless',
        category: 'wireless',
        shortDescription: 'Seamless roaming, high-density Access Point installation, RF heatmapping, captive guest portals, and high-throughput Point-to-Point links.',
        fullDescription: 'High-density enterprise Wi-Fi that just works. ABS Network deploys Access Points with seamless 802.11k/v/r roaming, RF channel optimization, guest portals with isolated VLANS, and long-range Point-to-Point and Point-to-Multipoint wireless links.',
        iconName: 'Wifi',
        badge: 'High Density',
        imageUrl: '/images/shop/abs-ac1200-ceiling-access-point.jpg',
        imageAlt: 'Enterprise Wi-Fi Access Points and Long Range Wireless Links',
        capabilities: [
          'High-density office & campus Wi-Fi deployment',
          'Seamless 802.11k/v/r roaming & RF channel optimization',
          'Guest Wi-Fi with isolated VLAN & bandwidth quotas',
          'Point-to-Point (PtP) & Point-to-Multipoint wireless links',
        ],
        features: [
          'Office & enterprise Wi-Fi installation',
          'Ceiling AP deployment & PoE layout',
          'Wireless coverage planning & RF heatmaps',
          'Guest portal & isolated guest VLANs',
          'Point-to-Point wireless links',
          'Point-to-multipoint links for multi-building campuses',
          'Wireless troubleshooting & interference cleanup',
        ],
        ctaLabel: 'Deploy Enterprise Wi-Fi',
        whatsappMessage: 'Hello ABS Network, I am interested in your Enterprise Wi-Fi and Wireless Solutions.',
        isFeatured: false,
        isPublished: true,
        displayOrder: 11,
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_cabling',
        title: 'Structured Cabling & Infrastructure',
        slug: 'structured-cabling-infrastructure',
        category: 'cabling',
        shortDescription: 'Certified Cat6/Cat6A and singlemode/multimode fiber optic cabling, server rack assembly, patch panel dressing, and laser-precise labeling.',
        fullDescription: 'A reliable network starts with a clean physical plant. ABS Network installs certified Cat5e, Cat6, and Cat6A copper drops, fiber optic backbones and splicing, server racks and cabinets, wire management, and Fluke/OTDR certified testing with precise labeling.',
        iconName: 'Cable',
        badge: 'Physical Plant',
        imageUrl: '/images/shop/fiber optics cable.jpg',
        imageAlt: 'Structured Cabling and Fiber Optic Infrastructure',
        capabilities: [
          'Cat5e, Cat6 & Cat6A high-bandwidth copper drops',
          'Fiber optic backbone splicing & patch panels',
          'Server room rack organization & vertical/horizontal wire management',
          'Fluke/OTDR cable testing, certification & labeling',
        ],
        features: [
          'Cat5e, Cat6 & Cat6A structured cabling',
          'Fiber optic infrastructure & termination',
          'Patch panels & keystone jack installation',
          'Network racks & server cabinets',
          'Cable management & tray routing',
          'Faceplates, keystone panels & labeling',
          'Cable testing, continuity & certification',
          'Server-room cabling revamp & cleanup',
        ],
        ctaLabel: 'Quote Cabling Project',
        whatsappMessage: 'Hello ABS Network, I am interested in Structured Cabling and physical network infrastructure.',
        isFeatured: false,
        isPublished: true,
        displayOrder: 12,
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_cctv',
        title: 'CCTV & Security Infrastructure',
        slug: 'cctv-security-infrastructure',
        category: 'cctv',
        shortDescription: 'High-definition IP surveillance cameras, NVR/storage arrays, PoE switch infrastructure, remote mobile viewing, and biometric access control.',
        fullDescription: 'Protect your premises with IP surveillance infrastructure. ABS Network installs HD IP cameras, designs PoE switch layouts, configures NVR storage and RAID, sets up encrypted remote viewing, and integrates access control and biometric security.',
        iconName: 'Video',
        badge: 'IP Surveillance',
        imageUrl: '/images/shop/rack&cabinet.jpg',
        imageAlt: 'IP CCTV Surveillance and Physical Security Networking',
        capabilities: [
          'IP CCTV camera placement & PoE network layout',
          'NVR storage calculation, RAID setup & configuration',
          'Encrypted remote viewing on mobile & desktop',
          'Access control & biometric security integration',
        ],
        features: [
          'IP CCTV camera installation',
          'CCTV dedicated network setup',
          'NVR configuration & storage planning',
          'Remote viewing configuration',
          'PoE switch layout & power budgeting',
          'Access control infrastructure',
          'Security network architecture',
        ],
        ctaLabel: 'Setup Surveillance',
        whatsappMessage: 'Hello ABS Network, I am interested in CCTV and security surveillance infrastructure.',
        isFeatured: false,
        isPublished: true,
        displayOrder: 13,
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_digital',
        title: 'Web & Digital Solutions',
        slug: 'web-digital-services',
        category: 'digital-services',
        shortDescription: 'High-performance corporate websites, bespoke web applications, UI/UX systems, technical SEO, and cloud DevOps deployment pipelines.',
        fullDescription: 'Accelerate your digital transformation. ABS Network builds high-performance corporate websites and web applications, designs UI/UX systems and responsive interfaces, delivers technical SEO and performance tuning, and manages DevOps, CI/CD, and cloud deployments.',
        iconName: 'Code',
        badge: 'Digital Engineering',
        imageUrl: '/hero.jpg',
        imageAlt: 'Custom Web Development and Digital Solutions',
        capabilities: [
          'Corporate websites, landing pages & web apps',
          'UI/UX design systems & responsive interfaces',
          'Technical SEO, performance tuning & core web vitals',
          'DevOps, CI/CD automation & cloud server deployment',
        ],
        features: [
          'Business & corporate websites',
          'Custom web applications & portals',
          'UI/UX design & interactive dashboards',
          'Technical SEO & speed optimization',
          'API integrations & business automation',
          'DevOps, CI/CD & Linux/Cloud deployment',
        ],
        ctaLabel: 'Start Digital Project',
        whatsappMessage: 'Hello ABS Network, I am interested in Web & Digital Solutions (Web Development, UI/UX, Custom Software).',
        isFeatured: true,
        isPublished: true,
        displayOrder: 14,
        seoTitle: 'Web & Digital Solutions | ABS Network',
        seoDescription: 'Corporate websites, web applications, UI/UX, technical SEO, and DevOps cloud deployment from ABS Network digital engineers.',
        seoKeywords: ['web development', 'web design', 'seo', 'ui ux', 'devops', 'cloud'],
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'srv_managed_it',
        title: 'Managed IT & Network Support',
        slug: 'managed-it-network-support',
        category: 'it-support',
        shortDescription: 'Comprehensive monthly SLA retainers covering proactive 24/7 network monitoring, server patching, scheduled maintenance, and priority engineer response.',
        fullDescription: 'Stay ahead of problems with a managed IT retainer. ABS Network provides proactive 24/7 network and server monitoring, preventive monthly maintenance and patching, guaranteed on-site and remote SLA response times, and strategic IT consulting.',
        iconName: 'Headphones',
        badge: '24/7 SLA Support',
        imageUrl: '/hero1.jpg',
        imageAlt: 'Managed IT and Network Operations Support',
        capabilities: [
          '24/7 proactive network & server monitoring',
          'Preventive monthly maintenance & patch updates',
          'Guaranteed on-site & remote SLA response times',
          'IT consulting, capacity planning & disaster recovery',
        ],
        features: [
          'Monthly IT support retainers',
          'Network & server uptime monitoring',
          'Preventive maintenance schedules',
          'Remote & on-site priority support',
          'Infrastructure health audits',
          'Backup monitoring & verification',
          'Network performance tuning',
          'Strategic IT consulting',
        ],
        ctaLabel: 'Talk to an IT Engineer',
        whatsappMessage: 'Hello ABS Network, I am interested in Managed IT & Network Support retainers for my organization.',
        isFeatured: false,
        isPublished: true,
        displayOrder: 15,
        publishedAt: now,
        createdAt: now,
        updatedAt: now,
      },
    ],
    shopProducts: [],
    contactSubmissions: [
      {
        id: 'sub_001',
        fullName: 'Muhammad Kamran',
        phone: '+92 321 5566778',
        email: 'kamran.k@example.com',
        subject: 'Inquiry for 75 Mbps Fiber Connection in Sector F-10',
        inquiryType: 'new_connection',
        packageInterest: 'ABS Ultra Gamer (75 Mbps)',
        message: 'Hello ABS Network team, I am moving into Sector F-10/2 and need a low-latency fiber connection for work and gaming. Can you verify fiber coverage on Street 14 and quote the earliest installation date?',
        status: 'new',
        ipAddress: '103.255.4.12',
        createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
        updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
      },
      {
        id: 'sub_002',
        fullName: 'Dr. Ayesha Siddiqui',
        phone: '+92 333 9876543',
        email: 'ayesha.clinic@example.com',
        subject: '100 Mbps Leased Line for Medical Diagnostic Center',
        inquiryType: 'sales',
        packageInterest: 'ABS Business Prime (100 Mbps)',
        message: 'We require a high-availability fiber line with static IP addresses for our imaging center PACS server and patient portal. Please send a corporate proposal and SLA terms.',
        status: 'in_review',
        assignedToStaff: 'Tariq Mehmood',
        internalNotes: 'Contacted client regarding site survey schedule. Proposal to be emailed today.',
        ipAddress: '110.39.12.88',
        createdAt: new Date(Date.now() - 3600000 * 22).toISOString(),
        updatedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
      },
      {
        id: 'sub_003',
        fullName: 'Shahbaz Ahmed',
        phone: '+92 300 4455667',
        email: 'shahbaz.a@example.com',
        subject: 'Enterprise Fiber Installation for Factory Campus',
        inquiryType: 'general',
        packageInterest: 'ABS Enterprise Apex (300 Mbps)',
        message: 'Looking for a fiber connection and network setup for our factory campus in Bahria Town Phase 7. Need consultation on structured cabling and enterprise network design.',
        status: 'contacted',
        assignedToStaff: 'Tariq Mehmood',
        internalNotes: 'Site survey scheduled for Friday 3:00 PM.',
        ipAddress: '39.40.180.201',
        createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
        updatedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
      },
    ],
    shopOrders: [],
    auditLogs: [
      {
        id: 'aud_init_01',
        action: 'SYSTEM_BOOTSTRAP',
        entityType: 'System',
        entityId: 'abs_network_core',
        userId: 'usr_admin_01',
        userEmail: 'admin@absnetwork.pk',
        details: { message: 'Initialized ABS Network database with fiber & networking shop architecture.' },
        ipAddress: '127.0.0.1',
        createdAt: now,
      },
    ],
    securityEvents: [
      {
        id: 'sec_001',
        eventType: 'LOGIN_SUCCESS',
        severity: 'INFO',
        description: 'Super Admin successfully authenticated from master terminal.',
        userId: 'usr_admin_01',
        userEmail: 'admin@absnetwork.pk',
        ipAddress: '127.0.0.1',
        createdAt: now,
      },
    ],
  };
}
